version: "3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: . # Change this line
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app # And this line
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/nginx/conf.d/fullchain.pem
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/nginx/conf.d/privkey.pem
    depends_on:
      - web

volumes:
  postgres_data:
