# Generated by Django 5.0.3 on 2024-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
